# Generated by Django 4.0.6 on 2022-07-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_online',
            new_name='is_playing',
        ),
    ]
