# Generated by Django 4.0.6 on 2022-07-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_is_online_customuser_is_playing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReallyBadChessStats',
            new_name='ConfusionChessStats',
        ),
        migrations.RenameField(
            model_name='userstats',
            old_name='really_bad_chess',
            new_name='confusion_chess',
        ),
    ]
