# Generated by Django 4.0.6 on 2022-07-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_reallybadchessstats_confusionchessstats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='confusion_chess',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='magic_chess',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='user',
        ),
        migrations.DeleteModel(
            name='ConfusionChessStats',
        ),
        migrations.DeleteModel(
            name='MagicChessStats',
        ),
        migrations.DeleteModel(
            name='UserStats',
        ),
    ]
