# Generated by Django 4.0.6 on 2022-07-23 16:18

import chess.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessMatch',
            fields=[
                ('id', models.SlugField(allow_unicode=True, default=chess.models.generate_id, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('really_bad_chess', 'Really bad chess'), ('magic_chess', 'Magic chess')], max_length=50)),
                ('black', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chess_match_black', to=settings.AUTH_USER_MODEL)),
                ('white', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chess_match_white', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
