# Generated by Django 4.0.6 on 2022-07-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessmatch',
            name='type',
            field=models.CharField(choices=[('confusion_chess', 'Confusion chess'), ('magic_chess', 'Magic chess')], max_length=50),
        ),
    ]
