# Generated by Django 4.0.6 on 2022-07-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0005_chessmatch_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessmatch',
            name='starting_pos',
            field=models.TextField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1'),
        ),
    ]
